/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "outline": "var(--color-outline)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary": "var(--color-on-primary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "primary": "var(--color-primary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary": "var(--color-tertiary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-error": "var(--color-on-error)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-background": "var(--color-on-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container": "var(--color-surface-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "background": "var(--color-background)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "primary-container": "var(--color-primary-container)",
        "error-container": "var(--color-error-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface": "var(--color-surface)",
        "error": "var(--color-error)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
    },
  },
  plugins: [],
}
